-- =============================================================================
-- SNOWFLAKE OPTIMIZATION DDL
-- Generated by: sybase-to-snowflake skill v0.3.0, Step 12
-- Pipeline:     run_20260402_001
-- Generated at: 2026-04-02
-- =============================================================================
--
-- 24 recommendations across 8 categories (O1-O8)
--   auto-apply:    17 (safe, additive changes)
--   manual-review:  7 (require architecture decisions or Enterprise Edition)
--
-- Replace {schema} with target schema (e.g., PUBLIC or INSURANCE_DW)
-- Replace {warehouse_name} with target warehouse name
-- =============================================================================


-- ═══════════════════════════════════════════════════════════════
-- AUTO-APPLY RECOMMENDATIONS
-- These are safe, additive changes approved for automatic application.
-- ═══════════════════════════════════════════════════════════════


-- ── O1: CLUSTERING KEYS ────────────────────────────────────────
-- Additive metadata; Automatic Clustering maintains ordering in background.
-- Benefit is conditional on table size exceeding ~1TB in production.

-- R001: fact_policy — range queries on date dimension keys
ALTER TABLE {schema}.fact_policy
  CLUSTER BY (effective_date_key, product_key);

-- R002: fact_claims — range queries on date dimension keys
ALTER TABLE {schema}.fact_claims
  CLUSTER BY (incident_date_key, policy_key);


-- ── O2: TRANSIENT TABLES ───────────────────────────────────────
-- Staging tables use truncate-reload pattern. TRANSIENT eliminates Fail-safe
-- storage (7 days → 0), reducing storage cost. Time Travel limited to 0-1 day.
--
-- NOTE: To apply, change CREATE OR REPLACE TABLE → CREATE OR REPLACE TRANSIENT TABLE
-- in the DDL files for each staging table. The ALTER below converts existing tables.

-- R003–R008: All 6 staging tables
ALTER TABLE {schema}.stg_policies   SET DATA_RETENTION_TIME_IN_DAYS = 0;
ALTER TABLE {schema}.stg_customers  SET DATA_RETENTION_TIME_IN_DAYS = 0;
ALTER TABLE {schema}.stg_claims     SET DATA_RETENTION_TIME_IN_DAYS = 0;
ALTER TABLE {schema}.stg_agents     SET DATA_RETENTION_TIME_IN_DAYS = 0;
ALTER TABLE {schema}.stg_products   SET DATA_RETENTION_TIME_IN_DAYS = 0;
ALTER TABLE {schema}.stg_payments   SET DATA_RETENTION_TIME_IN_DAYS = 0;
-- For new deployments, use CREATE OR REPLACE TRANSIENT TABLE in the DDL files instead.


-- ── O5: INFORMATIONAL CONSTRAINTS ──────────────────────────────
-- Not enforced by Snowflake. Zero runtime overhead.
-- Enables: BI tool auto-join inference + Snowflake optimizer join elimination.

-- R015: Dimension table primary keys
ALTER TABLE {schema}.dim_date     ADD CONSTRAINT pk_dim_date     PRIMARY KEY (date_key);
ALTER TABLE {schema}.dim_product  ADD CONSTRAINT pk_dim_product  PRIMARY KEY (product_key);
ALTER TABLE {schema}.dim_agent    ADD CONSTRAINT pk_dim_agent    PRIMARY KEY (agent_key);
ALTER TABLE {schema}.dim_customer ADD CONSTRAINT pk_dim_customer PRIMARY KEY (customer_key);

-- R012: fact_policy PK + FKs
ALTER TABLE {schema}.fact_policy ADD CONSTRAINT pk_fact_policy PRIMARY KEY (policy_key);
ALTER TABLE {schema}.fact_policy ADD CONSTRAINT fk_fp_dim_date
  FOREIGN KEY (effective_date_key) REFERENCES {schema}.dim_date (date_key);
ALTER TABLE {schema}.fact_policy ADD CONSTRAINT fk_fp_dim_product
  FOREIGN KEY (product_key) REFERENCES {schema}.dim_product (product_key);
ALTER TABLE {schema}.fact_policy ADD CONSTRAINT fk_fp_dim_agent
  FOREIGN KEY (agent_key) REFERENCES {schema}.dim_agent (agent_key);
ALTER TABLE {schema}.fact_policy ADD CONSTRAINT fk_fp_dim_customer
  FOREIGN KEY (customer_key) REFERENCES {schema}.dim_customer (customer_key);

-- R013: fact_claims PK + FKs
ALTER TABLE {schema}.fact_claims ADD CONSTRAINT pk_fact_claims PRIMARY KEY (claim_key);
ALTER TABLE {schema}.fact_claims ADD CONSTRAINT fk_fc_dim_date
  FOREIGN KEY (incident_date_key) REFERENCES {schema}.dim_date (date_key);
ALTER TABLE {schema}.fact_claims ADD CONSTRAINT fk_fc_dim_product
  FOREIGN KEY (product_key) REFERENCES {schema}.dim_product (product_key);
ALTER TABLE {schema}.fact_claims ADD CONSTRAINT fk_fc_dim_customer
  FOREIGN KEY (customer_key) REFERENCES {schema}.dim_customer (customer_key);
ALTER TABLE {schema}.fact_claims ADD CONSTRAINT fk_fc_fact_policy
  FOREIGN KEY (policy_key) REFERENCES {schema}.fact_policy (policy_key);

-- R014: fact_payments PK + FKs
ALTER TABLE {schema}.fact_payments ADD CONSTRAINT pk_fact_payments PRIMARY KEY (payment_key);
ALTER TABLE {schema}.fact_payments ADD CONSTRAINT fk_fpay_dim_customer
  FOREIGN KEY (customer_key) REFERENCES {schema}.dim_customer (customer_key);
ALTER TABLE {schema}.fact_payments ADD CONSTRAINT fk_fpay_fact_policy
  FOREIGN KEY (policy_key) REFERENCES {schema}.fact_policy (policy_key);


-- ── O8: STORAGE TUNING (DATA_RETENTION_TIME_IN_DAYS) ───────────
-- Set retention based on table type. Note: retention >1 day requires Enterprise Edition.

-- R019+R024: Staging tables — 1 day retention (transitory data)
ALTER TABLE {schema}.stg_policies  SET DATA_RETENTION_TIME_IN_DAYS = 1;
ALTER TABLE {schema}.stg_customers SET DATA_RETENTION_TIME_IN_DAYS = 1;
ALTER TABLE {schema}.stg_claims    SET DATA_RETENTION_TIME_IN_DAYS = 1;
ALTER TABLE {schema}.stg_agents    SET DATA_RETENTION_TIME_IN_DAYS = 1;
ALTER TABLE {schema}.stg_products  SET DATA_RETENTION_TIME_IN_DAYS = 1;
ALTER TABLE {schema}.stg_payments  SET DATA_RETENTION_TIME_IN_DAYS = 1;

-- R020: Dimension tables — 14 day retention (slowly changing data)
ALTER TABLE {schema}.dim_date     SET DATA_RETENTION_TIME_IN_DAYS = 14;
ALTER TABLE {schema}.dim_product  SET DATA_RETENTION_TIME_IN_DAYS = 14;
ALTER TABLE {schema}.dim_agent    SET DATA_RETENTION_TIME_IN_DAYS = 14;
ALTER TABLE {schema}.dim_customer SET DATA_RETENTION_TIME_IN_DAYS = 14;

-- R021: Fact tables — 90 day retention (audit trail, point-in-time recovery)
ALTER TABLE {schema}.fact_policy   SET DATA_RETENTION_TIME_IN_DAYS = 90;
ALTER TABLE {schema}.fact_claims   SET DATA_RETENTION_TIME_IN_DAYS = 90;
ALTER TABLE {schema}.fact_payments SET DATA_RETENTION_TIME_IN_DAYS = 90;

-- R022: Audit/log table — 90 day retention (compliance)
ALTER TABLE {schema}.etl_audit_log SET DATA_RETENTION_TIME_IN_DAYS = 90;

-- R023: Aggregation tables — 14 day retention (rebuildable from source)
ALTER TABLE {schema}.agg_policy_monthly SET DATA_RETENTION_TIME_IN_DAYS = 14;
ALTER TABLE {schema}.agg_claims_monthly SET DATA_RETENTION_TIME_IN_DAYS = 14;


-- ═══════════════════════════════════════════════════════════════
-- MANUAL REVIEW RECOMMENDATIONS
-- These require architecture decisions or Enterprise Edition.
-- Uncomment and modify as needed after review.
-- ═══════════════════════════════════════════════════════════════


-- ── O3: SEARCH OPTIMIZATION SERVICE ────────────────────────────
-- Requires: Enterprise Edition or higher
-- Incurs additional storage and compute cost for search access path maintenance.

-- [MANUAL REVIEW] R009: fact_policy — point lookups on policy_id, policy_number
-- ALTER TABLE {schema}.fact_policy
--   ADD SEARCH OPTIMIZATION ON EQUALITY(policy_id, policy_number);

-- [MANUAL REVIEW] R010: fact_claims — point lookups on claim_id, claim_number
-- ALTER TABLE {schema}.fact_claims
--   ADD SEARCH OPTIMIZATION ON EQUALITY(claim_id, claim_number);


-- ── O4: QUERY ACCELERATION SERVICE ─────────────────────────────
-- Requires: warehouse-level configuration decision with cost implications.

-- [MANUAL REVIEW] R011: Enable QAS for ad-hoc analytics workload
-- Replace {warehouse_name} with actual target warehouse.
-- ALTER WAREHOUSE {warehouse_name}
--   SET ENABLE_QUERY_ACCELERATION = TRUE
--       QUERY_ACCELERATION_MAX_SCALE_FACTOR = 8;


-- ── O6: DYNAMIC TABLE CANDIDATES ──────────────────────────────
-- Converts batch aggregation to declarative auto-refresh.
-- Fundamental change from batch-push to declarative-pull refresh model.

-- [MANUAL REVIEW] R016: agg_policy_monthly → Dynamic Table
-- Note: Cross-aggregate UPDATE from agg_claims_monthly would need separate handling.
-- CREATE OR REPLACE DYNAMIC TABLE {schema}.agg_policy_monthly
--   TARGET_LAG = '1 hour'
--   WAREHOUSE = {warehouse_name}
-- AS
--   {existing_select_from_fact_policy_dims};

-- [MANUAL REVIEW] R017: agg_claims_monthly → Dynamic Table
-- Note: Receives cross-aggregate UPDATE — must incorporate into SELECT or handle separately.
-- CREATE OR REPLACE DYNAMIC TABLE {schema}.agg_claims_monthly
--   TARGET_LAG = '1 hour'
--   WAREHOUSE = {warehouse_name}
-- AS
--   {existing_select_from_fact_claims_dims};


-- ── O7: STREAMS + TASKS MODERNIZATION ROADMAP ──────────────────
-- Fundamental architecture change from batch ETL to event-driven incremental.
-- This is advisory only — not executable DDL.

-- [MANUAL REVIEW] R018: Streams + Tasks DAG
--
-- Recommended Stream/Task pairs:
--   STREAM on stg_policies  → TASK to MERGE dim_product, dim_agent, dim_customer
--   STREAM on stg_customers → TASK to MERGE dim_customer (SCD2)
--   STREAM on stg_agents    → TASK to MERGE dim_agent (SCD2)
--   STREAM on stg_claims    → TASK to INSERT fact_claims
--   STREAM on stg_payments  → TASK to INSERT fact_payments
--
-- Task DAG root:
--   task_load_staging
--     → task_refresh_dims (dim_product, dim_agent, dim_customer)
--       → task_load_facts (fact_policy, fact_claims, fact_payments)
--         → task_refresh_aggs (agg_policy_monthly, agg_claims_monthly)
--
-- Benefits: Near-real-time refresh, reduced compute (process only changed rows),
-- built-in exactly-once semantics via Stream offsets.
