-- ================================================================
-- SIMPLE-TIER CONVERSION OUTPUT
-- Generated by: sybase-to-snowflake v0.3.0
-- Total objects: 9 (6 staging DDL, 2 views, 1 utility query)
-- Source series: basic (sql1.sql, sql5.sql)
-- Timestamp: 2026-04-02T00:00:00Z
-- ================================================================


-- ################################################################
-- OBJECT 1 of 9: stg_policies (TABLE)
-- ################################################################

-- ================================================================
-- Generated by: sybase-to-snowflake v0.3.0
-- Source: sql1.sql:31-119
-- Object: stg_policies (TABLE)
-- Block ID: sql1_001 + sql1_007
-- Complexity: Simple (score: 3)
-- Timestamp: 2026-04-02T00:00:00Z
-- Applied rules: §1:DATETIME→TIMESTAMP_NTZ, §1:DECIMAL→NUMBER, §2:GETDATE→CURRENT_TIMESTAMP, §3:IF_EXISTS/DROP/CREATE→CREATE_OR_REPLACE, §5:GO→removed
-- ================================================================

-- [REMOVE] IF EXISTS (SELECT 1 FROM sysobjects ...) / DROP TABLE — Snowflake uses CREATE OR REPLACE (type-map §3: IF EXISTS Pattern)
-- [REMOVE] GO — Snowflake uses semicolons (type-map §5: Batch and Control Flow)
-- [CONVERT] DECIMAL(18,2) → NUMBER(18,2) (type-map §1: Numeric Types)
-- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
-- [CONVERT] GETDATE() → CURRENT_TIMESTAMP() (type-map §2: Date/Time Functions)
CREATE OR REPLACE TABLE stg_policies (
    policy_id           BIGINT          NOT NULL,
    policy_number       VARCHAR(30)     NOT NULL,
    customer_id         BIGINT          NOT NULL,
    agent_id            INT             NOT NULL,
    product_code        VARCHAR(20)     NOT NULL,
    effective_date      DATE            NOT NULL,
    expiry_date         DATE            NOT NULL,
    status_code         CHAR(2)         NOT NULL,
    annual_premium      NUMBER(18,2)    NULL,
    coverage_amount     NUMBER(18,2)    NULL,
    territory_code      VARCHAR(10)     NULL,
    underwriter_id      INT             NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    created_date        TIMESTAMP_NTZ   NOT NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    last_updated        TIMESTAMP_NTZ   NOT NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    -- [CONVERT] GETDATE() → CURRENT_TIMESTAMP() (type-map §2: Date/Time Functions)
    src_extract_ts      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);


-- ################################################################
-- OBJECT 2 of 9: stg_customers (TABLE)
-- ################################################################

-- ================================================================
-- Generated by: sybase-to-snowflake v0.3.0
-- Source: sql1.sql:123-171
-- Object: stg_customers (TABLE)
-- Block ID: sql1_002 + sql1_008
-- Complexity: Simple (score: 3)
-- Timestamp: 2026-04-02T00:00:00Z
-- Applied rules: §1:DATETIME→TIMESTAMP_NTZ, §2:GETDATE→CURRENT_TIMESTAMP, §3:IF_EXISTS/DROP/CREATE→CREATE_OR_REPLACE, §5:GO→removed
-- ================================================================

-- [REMOVE] IF EXISTS (SELECT 1 FROM sysobjects ...) / DROP TABLE — Snowflake uses CREATE OR REPLACE (type-map §3: IF EXISTS Pattern)
-- [REMOVE] GO — Snowflake uses semicolons (type-map §5: Batch and Control Flow)
-- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
-- [CONVERT] GETDATE() → CURRENT_TIMESTAMP() (type-map §2: Date/Time Functions)
CREATE OR REPLACE TABLE stg_customers (
    customer_id         BIGINT          NOT NULL,
    first_name          VARCHAR(100)    NULL,
    last_name           VARCHAR(100)    NULL,
    date_of_birth       DATE            NULL,
    gender_code         CHAR(1)         NULL,
    marital_status      CHAR(1)         NULL,
    address_line1       VARCHAR(200)    NULL,
    address_line2       VARCHAR(200)    NULL,
    city                VARCHAR(100)    NULL,
    state_code          CHAR(2)         NULL,
    zip_code            VARCHAR(10)     NULL,
    email               VARCHAR(150)    NULL,
    phone_primary       VARCHAR(20)     NULL,
    credit_score        SMALLINT        NULL,
    customer_segment    VARCHAR(30)     NULL,
    acquisition_source  VARCHAR(50)     NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    created_date        TIMESTAMP_NTZ   NOT NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    last_updated        TIMESTAMP_NTZ   NOT NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    -- [CONVERT] GETDATE() → CURRENT_TIMESTAMP() (type-map §2: Date/Time Functions)
    src_extract_ts      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);


-- ################################################################
-- OBJECT 3 of 9: stg_claims (TABLE)
-- ################################################################

-- ================================================================
-- Generated by: sybase-to-snowflake v0.3.0
-- Source: sql1.sql:175-221
-- Object: stg_claims (TABLE)
-- Block ID: sql1_003 + sql1_009
-- Complexity: Simple (score: 3)
-- Timestamp: 2026-04-02T00:00:00Z
-- Applied rules: §1:DATETIME→TIMESTAMP_NTZ, §1:DECIMAL→NUMBER, §2:GETDATE→CURRENT_TIMESTAMP, §3:IF_EXISTS/DROP/CREATE→CREATE_OR_REPLACE, §5:GO→removed
-- ================================================================

-- [REMOVE] IF EXISTS (SELECT 1 FROM sysobjects ...) / DROP TABLE — Snowflake uses CREATE OR REPLACE (type-map §3: IF EXISTS Pattern)
-- [REMOVE] GO — Snowflake uses semicolons (type-map §5: Batch and Control Flow)
-- [CONVERT] DECIMAL(18,2) → NUMBER(18,2) (type-map §1: Numeric Types)
-- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
-- [CONVERT] GETDATE() → CURRENT_TIMESTAMP() (type-map §2: Date/Time Functions)
CREATE OR REPLACE TABLE stg_claims (
    claim_id            BIGINT          NOT NULL,
    claim_number        VARCHAR(30)     NOT NULL,
    policy_id           BIGINT          NOT NULL,
    customer_id         BIGINT          NOT NULL,
    incident_date       DATE            NOT NULL,
    reported_date       DATE            NOT NULL,
    closed_date         DATE            NULL,
    claim_type_code     VARCHAR(20)     NOT NULL,
    status_code         VARCHAR(10)     NOT NULL,
    -- [CONVERT] DECIMAL(18,2) → NUMBER(18,2) (type-map §1: Numeric Types)
    total_incurred      NUMBER(18,2)    NULL,
    -- [CONVERT] DECIMAL(18,2) → NUMBER(18,2) (type-map §1: Numeric Types)
    total_paid          NUMBER(18,2)    NULL,
    -- [CONVERT] DECIMAL(18,2) → NUMBER(18,2) (type-map §1: Numeric Types)
    total_reserved      NUMBER(18,2)    NULL,
    adjuster_id         INT             NULL,
    fault_indicator     CHAR(1)         NULL,
    litigation_flag     CHAR(1)         NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    created_date        TIMESTAMP_NTZ   NOT NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    last_updated        TIMESTAMP_NTZ   NOT NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    -- [CONVERT] GETDATE() → CURRENT_TIMESTAMP() (type-map §2: Date/Time Functions)
    src_extract_ts      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);


-- ################################################################
-- OBJECT 4 of 9: stg_agents (TABLE)
-- ################################################################

-- ================================================================
-- Generated by: sybase-to-snowflake v0.3.0
-- Source: sql1.sql:225-267
-- Object: stg_agents (TABLE)
-- Block ID: sql1_004 + sql1_010
-- Complexity: Simple (score: 3)
-- Timestamp: 2026-04-02T00:00:00Z
-- Applied rules: §1:DATETIME→TIMESTAMP_NTZ, §2:GETDATE→CURRENT_TIMESTAMP, §3:IF_EXISTS/DROP/CREATE→CREATE_OR_REPLACE, §5:GO→removed
-- ================================================================

-- [REMOVE] IF EXISTS (SELECT 1 FROM sysobjects ...) / DROP TABLE — Snowflake uses CREATE OR REPLACE (type-map §3: IF EXISTS Pattern)
-- [REMOVE] GO — Snowflake uses semicolons (type-map §5: Batch and Control Flow)
-- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
-- [CONVERT] GETDATE() → CURRENT_TIMESTAMP() (type-map §2: Date/Time Functions)
CREATE OR REPLACE TABLE stg_agents (
    agent_id            INT             NOT NULL,
    agent_number        VARCHAR(20)     NOT NULL,
    agent_name          VARCHAR(200)    NOT NULL,
    agency_id           INT             NULL,
    agency_name         VARCHAR(200)    NULL,
    license_state       CHAR(2)         NULL,
    license_number      VARCHAR(30)     NULL,
    license_expiry      DATE            NULL,
    region_code         VARCHAR(10)     NULL,
    channel_code        VARCHAR(20)     NULL,   -- INDEPENDENT, CAPTIVE, DIRECT
    active_flag         CHAR(1)         NOT NULL DEFAULT 'Y',
    hire_date           DATE            NULL,
    termination_date    DATE            NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    created_date        TIMESTAMP_NTZ   NOT NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    last_updated        TIMESTAMP_NTZ   NOT NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    -- [CONVERT] GETDATE() → CURRENT_TIMESTAMP() (type-map §2: Date/Time Functions)
    src_extract_ts      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);


-- ################################################################
-- OBJECT 5 of 9: stg_products (TABLE)
-- ################################################################

-- ================================================================
-- Generated by: sybase-to-snowflake v0.3.0
-- Source: sql1.sql:271-311
-- Object: stg_products (TABLE)
-- Block ID: sql1_005 + sql1_011
-- Complexity: Simple (score: 2)
-- Timestamp: 2026-04-02T00:00:00Z
-- Applied rules: §1:DATETIME→TIMESTAMP_NTZ, §1:DECIMAL→NUMBER, §2:GETDATE→CURRENT_TIMESTAMP, §3:IF_EXISTS/DROP/CREATE→CREATE_OR_REPLACE, §5:GO→removed
-- ================================================================

-- [REMOVE] IF EXISTS (SELECT 1 FROM sysobjects ...) / DROP TABLE — Snowflake uses CREATE OR REPLACE (type-map §3: IF EXISTS Pattern)
-- [REMOVE] GO — Snowflake uses semicolons (type-map §5: Batch and Control Flow)
-- [CONVERT] DECIMAL(18,2) → NUMBER(18,2) (type-map §1: Numeric Types)
-- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
-- [CONVERT] GETDATE() → CURRENT_TIMESTAMP() (type-map §2: Date/Time Functions)
CREATE OR REPLACE TABLE stg_products (
    product_code        VARCHAR(20)     NOT NULL,
    product_name        VARCHAR(150)    NOT NULL,
    product_line        VARCHAR(50)     NULL,   -- AUTO, HOME, COMMERCIAL, LIFE
    lob_code            VARCHAR(20)     NULL,
    sub_lob_code        VARCHAR(20)     NULL,
    coverage_type       VARCHAR(50)     NULL,
    rating_plan         VARCHAR(30)     NULL,
    -- [CONVERT] DECIMAL(18,2) → NUMBER(18,2) (type-map §1: Numeric Types)
    min_premium         NUMBER(18,2)    NULL,
    -- [CONVERT] DECIMAL(18,2) → NUMBER(18,2) (type-map §1: Numeric Types)
    max_coverage        NUMBER(18,2)    NULL,
    active_flag         CHAR(1)         NOT NULL DEFAULT 'Y',
    effective_date      DATE            NULL,
    discontinue_date    DATE            NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    created_date        TIMESTAMP_NTZ   NOT NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    last_updated        TIMESTAMP_NTZ   NOT NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    -- [CONVERT] GETDATE() → CURRENT_TIMESTAMP() (type-map §2: Date/Time Functions)
    src_extract_ts      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);


-- ################################################################
-- OBJECT 6 of 9: stg_payments (TABLE)
-- ################################################################

-- ================================================================
-- Generated by: sybase-to-snowflake v0.3.0
-- Source: sql1.sql:315-355
-- Object: stg_payments (TABLE)
-- Block ID: sql1_006 + sql1_012
-- Complexity: Simple (score: 2)
-- Timestamp: 2026-04-02T00:00:00Z
-- Applied rules: §1:DATETIME→TIMESTAMP_NTZ, §1:DECIMAL→NUMBER, §2:GETDATE→CURRENT_TIMESTAMP, §3:IF_EXISTS/DROP/CREATE→CREATE_OR_REPLACE, §5:GO→removed
-- ================================================================

-- [REMOVE] IF EXISTS (SELECT 1 FROM sysobjects ...) / DROP TABLE — Snowflake uses CREATE OR REPLACE (type-map §3: IF EXISTS Pattern)
-- [REMOVE] GO — Snowflake uses semicolons (type-map §5: Batch and Control Flow)
-- [CONVERT] DECIMAL(18,2) → NUMBER(18,2) (type-map §1: Numeric Types)
-- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
-- [CONVERT] GETDATE() → CURRENT_TIMESTAMP() (type-map §2: Date/Time Functions)
CREATE OR REPLACE TABLE stg_payments (
    payment_id          BIGINT          NOT NULL,
    policy_id           BIGINT          NOT NULL,
    customer_id         BIGINT          NOT NULL,
    payment_date        DATE            NOT NULL,
    due_date            DATE            NULL,
    -- [CONVERT] DECIMAL(18,2) → NUMBER(18,2) (type-map §1: Numeric Types)
    payment_amount      NUMBER(18,2)    NOT NULL,
    payment_method      VARCHAR(30)     NULL,   -- CHECK, ACH, CREDIT_CARD
    payment_status      VARCHAR(20)     NOT NULL,
    invoice_number      VARCHAR(30)     NULL,
    installment_number  SMALLINT        NULL,
    late_flag           CHAR(1)         NULL,
    nsf_flag            CHAR(1)         NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    created_date        TIMESTAMP_NTZ   NOT NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    last_updated        TIMESTAMP_NTZ   NOT NULL,
    -- [CONVERT] DATETIME → TIMESTAMP_NTZ (type-map §1: Date/Time Types)
    -- [CONVERT] GETDATE() → CURRENT_TIMESTAMP() (type-map §2: Date/Time Functions)
    src_extract_ts      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);


-- ################################################################
-- OBJECT 7 of 9: v_policy_detail (VIEW)
-- ################################################################

-- ================================================================
-- Generated by: sybase-to-snowflake v0.3.0
-- Source: sql5.sql:401-511
-- Object: v_policy_detail (VIEW)
-- Block ID: sql5_v_policy_detail
-- Complexity: Simple (score: 3)
-- Timestamp: 2026-04-02T00:00:00Z
-- Applied rules: §3:IF_EXISTS/DROP/CREATE→CREATE_OR_REPLACE, §5:GO→removed
-- ================================================================

-- [REMOVE] IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'v_policy_detail' AND type = 'V') / DROP VIEW — Snowflake uses CREATE OR REPLACE (type-map §3: IF EXISTS Pattern)
-- [REMOVE] GO — Snowflake uses semicolons (type-map §5: Batch and Control Flow)
CREATE OR REPLACE VIEW v_policy_detail AS
SELECT
    fp.policy_id,
    fp.policy_number,
    fp.status_code,
    fp.territory_code,
    fp.annual_premium,
    fp.coverage_amount,
    fp.earned_premium_amount,
    fp.policy_term_days,
    -- Customer attributes
    dc.customer_id,
    dc.full_name             AS customer_name,
    dc.age_band,
    dc.gender_description,
    dc.marital_description,
    dc.city,
    dc.state_code,
    dc.state_name,
    dc.region,
    dc.credit_band,
    dc.customer_segment,
    dc.acquisition_source,
    -- Agent attributes
    da.agent_id,
    da.agent_name,
    da.agency_name,
    da.region_description    AS agent_region,
    da.channel_description   AS distribution_channel,
    -- Product attributes
    dp.product_code,
    dp.product_name,
    dp.product_line,
    dp.lob_code,
    dp.lob_description,
    dp.coverage_type,
    -- Date attributes (effective)
    dd_eff.calendar_date     AS effective_date,
    dd_eff.year_number       AS eff_year,
    dd_eff.month_name        AS eff_month,
    dd_eff.quarter_name      AS eff_quarter,
    dd_eff.fiscal_year       AS eff_fiscal_year,
    -- Date attributes (expiry)
    dd_exp.calendar_date     AS expiry_date,
    dd_exp.year_number       AS exp_year
FROM fact_policy fp
INNER JOIN dim_customer dc  ON dc.customer_key  = fp.customer_key
INNER JOIN dim_agent    da  ON da.agent_key     = fp.agent_key
INNER JOIN dim_product  dp  ON dp.product_key   = fp.product_key
INNER JOIN dim_date  dd_eff ON dd_eff.date_key  = fp.effective_date_key
INNER JOIN dim_date  dd_exp ON dd_exp.date_key  = fp.expiry_date_key;


-- ################################################################
-- OBJECT 8 of 9: v_claims_analysis (VIEW)
-- ################################################################

-- ================================================================
-- Generated by: sybase-to-snowflake v0.3.0
-- Source: sql5.sql:517-621
-- Object: v_claims_analysis (VIEW)
-- Block ID: sql5_v_claims_analysis
-- Complexity: Simple (score: 3)
-- Timestamp: 2026-04-02T00:00:00Z
-- Applied rules: §3:IF_EXISTS/DROP/CREATE→CREATE_OR_REPLACE, §5:GO→removed
-- ================================================================

-- [REMOVE] IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'v_claims_analysis' AND type = 'V') / DROP VIEW — Snowflake uses CREATE OR REPLACE (type-map §3: IF EXISTS Pattern)
-- [REMOVE] GO — Snowflake uses semicolons (type-map §5: Batch and Control Flow)
CREATE OR REPLACE VIEW v_claims_analysis AS
SELECT
    fc.claim_id,
    fc.claim_number,
    fc.policy_id,
    fc.claim_type_code,
    fc.status_code           AS claim_status,
    fc.fault_indicator,
    fc.litigation_flag,
    fc.total_incurred,
    fc.total_paid,
    fc.total_reserved,
    fc.outstanding_reserve,
    fc.claim_report_lag_days,
    fc.claim_settlement_days,
    fc.loss_ratio_pct,
    -- Customer
    dc.full_name             AS customer_name,
    dc.state_code,
    dc.state_name,
    dc.region,
    dc.credit_band,
    dc.customer_segment,
    -- Product
    dp.product_line,
    dp.lob_code,
    dp.lob_description,
    dp.coverage_type,
    -- Policy premium context
    fp.annual_premium        AS policy_annual_premium,
    fp.earned_premium_amount,
    -- Incident date
    dd_inc.calendar_date     AS incident_date,
    dd_inc.year_number       AS incident_year,
    dd_inc.month_name        AS incident_month,
    dd_inc.quarter_name      AS incident_quarter,
    dd_inc.fiscal_year       AS incident_fiscal_year,
    -- Reported date
    dd_rep.calendar_date     AS reported_date,
    -- Closed date
    dd_cls.calendar_date     AS closed_date
FROM fact_claims fc
INNER JOIN dim_customer dc  ON dc.customer_key      = fc.customer_key
INNER JOIN fact_policy  fp  ON fp.policy_id         = fc.policy_id
INNER JOIN dim_product  dp  ON dp.product_key       = fp.product_key
INNER JOIN dim_date  dd_inc ON dd_inc.date_key      = fc.incident_date_key
INNER JOIN dim_date  dd_rep ON dd_rep.date_key      = fc.reported_date_key
LEFT  JOIN dim_date  dd_cls ON dd_cls.date_key      = fc.closed_date_key;


-- ################################################################
-- OBJECT 9 of 9: Row Count Validation Query (UTILITY)
-- ################################################################

-- ================================================================
-- Generated by: sybase-to-snowflake v0.3.0
-- Source: sql1.sql:659-681
-- Object: row_count_validation (UTILITY)
-- Block ID: sql1_019
-- Complexity: Simple (score: 0)
-- Timestamp: 2026-04-02T00:00:00Z
-- Applied rules: §5:GO→removed
-- ================================================================

-- [REMOVE] GO — Snowflake uses semicolons (type-map §5: Batch and Control Flow)
SELECT 'stg_policies'  AS table_name, COUNT(*) AS row_count FROM stg_policies
UNION ALL
SELECT 'stg_customers',                COUNT(*)              FROM stg_customers
UNION ALL
SELECT 'stg_claims',                   COUNT(*)              FROM stg_claims
UNION ALL
SELECT 'stg_agents',                   COUNT(*)              FROM stg_agents
UNION ALL
SELECT 'stg_products',                 COUNT(*)              FROM stg_products
UNION ALL
SELECT 'stg_payments',                 COUNT(*)              FROM stg_payments;
