-- =============================================================================
-- [META] Generated by: sybase-to-snowflake skill v0.2.0
-- [META] Purpose:       Test execution script — runs converted SQL against seed data
-- [META] Converted at:  2026-04-02
-- =============================================================================
--
-- Execution order follows dependency_graph.json topological sort:
--   Layer 0: DDL staging → seed data → DDL dimensions → DDL facts → DDL audit
--   Layer 1: DML dim_date (GENERATOR)
--   Layer 2: DML dim_product (MERGE / SCD1)
--   Layer 3: DML dim_agent (SCD2 — initial load)
--   Layer 4: DML dim_customer (SCD2 — initial load)
--   Layer 5: DML fact_policy, fact_claims, fact_payments
--   Layer 6: DML aggregation + cross-aggregate UPDATE
--   Layer 7: DDL views
--   Layer 8: Stored procedure (DQ checks)
--
-- Prerequisites:
--   1. Create a test schema:  CREATE SCHEMA IF NOT EXISTS <db>._SYBASE_MIGRATION_TEST;
--   2. USE SCHEMA <db>._SYBASE_MIGRATION_TEST;
--   3. Run this script in order (each statement separated by ;)
-- =============================================================================


-- ============================================================
-- LAYER 0: DDL — Create all tables
-- ============================================================

-- Run: output/ddl_staging.sql    (6 staging tables)
-- Run: output/ddl_dimensions.sql (4 dimension tables)
-- Run: output/ddl_facts.sql      (3 fact tables)
-- Run: output/ddl_audit.sql      (1 audit table)

-- Then load seed data:
-- Run: output/tests/seed_data.sql

-- Then create test infrastructure:
-- Run: output/tests/test_ddl.sql


-- ============================================================
-- LAYER 1: dim_date — GENERATOR INSERT
-- ============================================================
-- Run: output/dml_dimensions.sql (dim_date INSERT section only)
-- Verify:
SELECT 'dim_date_row_count' AS test_name,
       COUNT(*)             AS actual_value,
       11323                AS expected_value,
       CASE WHEN COUNT(*) = 11323 THEN 'PASS' ELSE 'FAIL' END AS result
FROM dim_date;


-- ============================================================
-- LAYER 2: dim_product — MERGE (SCD1)
-- ============================================================
-- Run: output/dml_dimensions.sql (dim_product MERGE section)
-- Verify:
SELECT 'dim_product_load_count' AS test_name,
       COUNT(*)                 AS actual_value,
       6                        AS expected_value,
       CASE WHEN COUNT(*) = 6 THEN 'PASS' ELSE 'FAIL' END AS result
FROM dim_product;


-- ============================================================
-- LAYER 3: dim_agent — SCD2 initial load
-- ============================================================
-- Run: output/dml_dimensions.sql (dim_agent INSERT section)
-- Note: SCD2 expire UPDATE won't fire on initial load (no prior records)
-- Verify:
SELECT 'dim_agent_initial_count' AS test_name,
       COUNT(*)                  AS actual_value,
       5                         AS expected_value,
       CASE WHEN COUNT(*) = 5 THEN 'PASS' ELSE 'FAIL' END AS result
FROM dim_agent
WHERE scd_current_flag = 'Y';


-- ============================================================
-- LAYER 4: dim_customer — SCD2 initial load
-- ============================================================
-- Run: output/dml_dimensions.sql (dim_customer expire UPDATE, then INSERT)
-- Verify:
SELECT 'dim_customer_initial_count' AS test_name,
       COUNT(*)                     AS actual_value,
       8                            AS expected_value,
       CASE WHEN COUNT(*) = 8 THEN 'PASS' ELSE 'FAIL' END AS result
FROM dim_customer
WHERE scd_current_flag = 'Y';


-- ============================================================
-- LAYER 5: fact tables
-- ============================================================
-- Run: output/dml_facts.sql (fact_policy INSERT, fact_claims INSERT, fact_payments INSERT)

-- Verify fact_policy:
SELECT 'fact_policy_load_count' AS test_name,
       COUNT(*)                 AS actual_value,
       10                       AS expected_value,
       CASE WHEN COUNT(*) = 10 THEN 'PASS' ELSE 'FAIL' END AS result
FROM fact_policy;

-- Verify fact_claims:
SELECT 'fact_claims_load_count' AS test_name,
       COUNT(*)                 AS actual_value,
       6                        AS expected_value,
       CASE WHEN COUNT(*) = 6 THEN 'PASS' ELSE 'FAIL' END AS result
FROM fact_claims;

-- Verify fact_payments:
SELECT 'fact_payments_load_count' AS test_name,
       COUNT(*)                   AS actual_value,
       6                          AS expected_value,
       CASE WHEN COUNT(*) = 6 THEN 'PASS' ELSE 'FAIL' END AS result
FROM fact_payments;


-- ============================================================
-- LAYER 6: Aggregation
-- ============================================================
-- Run: output/dml_aggregation.sql (agg_policy_monthly DDL+DML, agg_claims_monthly DDL+DML)
-- Then run: cross-aggregate UPDATE from output/dml_aggregation.sql

-- Verify:
SELECT 'agg_policy_monthly_populated' AS test_name,
       COUNT(*)                       AS actual_value,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM agg_policy_monthly;

SELECT 'agg_claims_monthly_populated' AS test_name,
       COUNT(*)                       AS actual_value,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM agg_claims_monthly;


-- ============================================================
-- LAYER 7: Views
-- ============================================================
-- Run: output/ddl_views.sql (v_policy_detail, v_claims_analysis, v_exec_kpi_summary)

-- Verify views return data:
SELECT 'v_policy_detail_returns_rows' AS test_name,
       COUNT(*)                       AS actual_value,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM v_policy_detail;

SELECT 'v_claims_analysis_returns_rows' AS test_name,
       COUNT(*)                         AS actual_value,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM v_claims_analysis;

SELECT 'v_exec_kpi_summary_returns_rows' AS test_name,
       COUNT(*)                          AS actual_value,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM v_exec_kpi_summary;


-- ============================================================
-- LAYER 8: Stored procedure — DQ checks
-- ============================================================
-- Run: output/proc_etl_dq_checks.sql (CREATE OR REPLACE PROCEDURE)

-- Test PASS path (batch_id = 9001 — seed data should have some DQ issues):
-- Note: This will RAISE if DQ checks fail (expected with edge-case seed data).
-- For clean-path testing, insert only the 6 happy-path rows first.

-- CALL sp_etl_dq_checks(9001);

-- Verify audit log entries:
SELECT 'dq_audit_log_populated' AS test_name,
       COUNT(*)                 AS actual_value,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM etl_audit_log
WHERE batch_id = 9001;


-- ============================================================
-- SUMMARY: Collect all test results
-- ============================================================
-- After running all layers above, execute reconciliation_queries.sql
-- for the full 40-test validation suite.
