-- =============================================================================
-- [META] Generated by: sybase-to-snowflake skill v0.2.0
-- [META] Purpose:       Test infrastructure DDL for validation harness
-- [META] Converted at:  2026-04-02
-- =============================================================================
--
-- Creates:
--   1. test_expected_results — expected outcome reference table
--   2. test_execution_log   — records test run results
-- =============================================================================


-- ============================================================
-- Test expected results reference
-- ============================================================
CREATE OR REPLACE TABLE test_expected_results (
    test_id             INT             NOT NULL,
    test_name           VARCHAR(200)    NOT NULL,
    test_category       VARCHAR(50)     NOT NULL,   -- DIM_DATE, SCD1, SCD2, FACT, DQ, AGG, VIEW
    target_object       VARCHAR(100)    NOT NULL,
    assertion_type      VARCHAR(30)     NOT NULL,   -- ROW_COUNT, VALUE_CHECK, EXISTS, NOT_EXISTS, RANGE
    expected_value      VARCHAR(500)    NULL,
    description         VARCHAR(500)    NOT NULL,
    PRIMARY KEY (test_id)
);

-- ============================================================
-- Test execution log
-- ============================================================
CREATE OR REPLACE TABLE test_execution_log (
    run_id              INT AUTOINCREMENT NOT NULL PRIMARY KEY,
    test_id             INT             NOT NULL,
    test_name           VARCHAR(200)    NOT NULL,
    executed_at         TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    actual_value        VARCHAR(500)    NULL,
    expected_value      VARCHAR(500)    NULL,
    result              VARCHAR(10)     NOT NULL,   -- PASS, FAIL, ERROR
    error_message       VARCHAR(1000)   NULL
);


-- ============================================================
-- Populate expected results (40 test cases)
-- ============================================================
INSERT INTO test_expected_results VALUES

-- ---- DIM_DATE TESTS ----
(1,  'dim_date_row_count',            'DIM_DATE', 'dim_date', 'ROW_COUNT',  '11323',      'GENERATOR produces exactly 11,323 rows (2000-01-01 to 2030-12-31)'),
(2,  'dim_date_start_boundary',       'DIM_DATE', 'dim_date', 'EXISTS',     '20000101',   'First date key = 2000-01-01'),
(3,  'dim_date_end_boundary',         'DIM_DATE', 'dim_date', 'EXISTS',     '20301231',   'Last date key = 2030-12-31'),
(4,  'dim_date_leap_day',             'DIM_DATE', 'dim_date', 'EXISTS',     '20240229',   'Leap day 2024-02-29 present'),
(5,  'dim_date_month_end_flag',       'DIM_DATE', 'dim_date', 'VALUE_CHECK','Y',          '2024-01-31 has is_month_end = Y'),
(6,  'dim_date_year_end_flag',        'DIM_DATE', 'dim_date', 'VALUE_CHECK','Y',          '2024-12-31 has is_year_end = Y'),
(7,  'dim_date_fiscal_year_apr',      'DIM_DATE', 'dim_date', 'VALUE_CHECK','2024',       '2024-04-01 fiscal_year = 2024 (Apr = FY start)'),
(8,  'dim_date_fiscal_year_mar',      'DIM_DATE', 'dim_date', 'VALUE_CHECK','2023',       '2024-03-31 fiscal_year = 2023 (Mar = prior FY)'),

-- ---- DIM_PRODUCT SCD1 MERGE TESTS ----
(10, 'dim_product_initial_load_count','SCD1',     'dim_product', 'ROW_COUNT','6',         '6 products loaded on initial insert'),
(11, 'dim_product_lob_auto',          'SCD1',     'dim_product', 'VALUE_CHECK','Personal Auto', 'AUTO-01 lob_description = Personal Auto'),
(12, 'dim_product_lob_life',          'SCD1',     'dim_product', 'VALUE_CHECK','Life and Annuity', 'LIFE-01 lob_description = Life and Annuity'),
(13, 'dim_product_inactive_flag',     'SCD1',     'dim_product', 'VALUE_CHECK','N',       'LIFE-01 is_active = N (discontinued)'),

-- ---- DIM_AGENT SCD2 TESTS ----
(20, 'dim_agent_initial_count',       'SCD2',     'dim_agent', 'ROW_COUNT', '5',          '5 agent records on initial load'),
(21, 'dim_agent_scd_current_flag',    'SCD2',     'dim_agent', 'ROW_COUNT', '5',          'All 5 initial records have scd_current_flag = Y'),
(22, 'dim_agent_inactive_preserved',  'SCD2',     'dim_agent', 'VALUE_CHECK','N',         'Agent 104 is_active = N preserved'),

-- ---- DIM_CUSTOMER SCD2 TESTS ----
(30, 'dim_cust_initial_count',        'SCD2',     'dim_customer', 'ROW_COUNT','8',        '8 customer records on initial load'),
(31, 'dim_cust_credit_exceptional',   'SCD2',     'dim_customer', 'VALUE_CHECK','Exceptional (800+)', 'Customer 5004 credit_band = Exceptional (800+) [score=800]'),
(32, 'dim_cust_credit_very_good',     'SCD2',     'dim_customer', 'VALUE_CHECK','Very Good (740-799)','Customer 5001 credit_band = Very Good (740-799) [score=780]'),
(33, 'dim_cust_credit_good',          'SCD2',     'dim_customer', 'VALUE_CHECK','Good (670-739)',     'Customer 5003 credit_band = Good (670-739) [score=670]'),
(34, 'dim_cust_credit_fair',          'SCD2',     'dim_customer', 'VALUE_CHECK','Fair (580-669)',     'Customer 5002 credit_band = Fair (580-669) [score=580]'),
(35, 'dim_cust_credit_poor',          'SCD2',     'dim_customer', 'VALUE_CHECK','Poor (<580)',        'Customer 5007 credit_band = Poor (<580) [score=520]'),
(36, 'dim_cust_credit_unknown',       'SCD2',     'dim_customer', 'VALUE_CHECK','Unknown',            'Customer 5005 credit_band = Unknown [NULL score]'),
(37, 'dim_cust_region_northeast',     'SCD2',     'dim_customer', 'VALUE_CHECK','Northeast',          'Customer 5001 region = Northeast [state=CT]'),
(38, 'dim_cust_region_southeast',     'SCD2',     'dim_customer', 'VALUE_CHECK','Southeast',          'Customer 5002 region = Southeast [state=FL]'),
(39, 'dim_cust_region_west',          'SCD2',     'dim_customer', 'VALUE_CHECK','West',               'Customer 5004 region = West [state=CA]'),

-- ---- FACT_POLICY TESTS ----
(40, 'fact_policy_load_count',        'FACT',     'fact_policy', 'ROW_COUNT','10',        '10 policies loaded'),
(41, 'fact_policy_date_key_format',   'FACT',     'fact_policy', 'VALUE_CHECK','20240115','Policy 1001 effective_date_key = 20240115'),
(42, 'fact_policy_unresolved_key',    'FACT',     'fact_policy', 'VALUE_CHECK','-1',      'Unresolved surrogate keys default to -1'),
(43, 'fact_policy_term_days',         'FACT',     'fact_policy', 'VALUE_CHECK','366',     'Policy 1001 term_days = 366 (2024 leap year)'),

-- ---- FACT_CLAIMS TESTS ----
(50, 'fact_claims_load_count',        'FACT',     'fact_claims', 'ROW_COUNT','6',         '6 claims loaded'),
(51, 'fact_claims_report_lag',        'FACT',     'fact_claims', 'VALUE_CHECK','2',       'Claim 3001 report_lag_days = 2 (Jun 1 → Jun 3)'),
(52, 'fact_claims_settlement_days',   'FACT',     'fact_claims', 'VALUE_CHECK','73',      'Claim 3001 settlement_days = 73 (Jun 3 → Aug 15)'),
(53, 'fact_claims_null_closed_key',   'FACT',     'fact_claims', 'VALUE_CHECK','NULL',    'Claim 3002 closed_date_key IS NULL (open claim)'),

-- ---- ETL DQ CHECKS TESTS ----
(60, 'dq_pass_path',                  'DQ',       'sp_etl_dq_checks', 'VALUE_CHECK','PASS','DQ procedure returns PASS with clean data'),
(61, 'dq_negative_premium_detect',    'DQ',       'etl_audit_log', 'EXISTS','FAIL',       'Negative premium row triggers DQ failure'),
(62, 'dq_orphan_claim_detect',        'DQ',       'etl_audit_log', 'EXISTS','FAIL',       'Orphan claim (policy 9999) triggers referential check failure'),

-- ---- AGGREGATION TESTS ----
(70, 'agg_policy_monthly_populated',  'AGG',      'agg_policy_monthly', 'ROW_COUNT','>0', 'agg_policy_monthly has rows after load'),
(71, 'agg_cross_update_loss_ratio',   'AGG',      'agg_claims_monthly', 'NOT_EXISTS','NULL','loss_ratio_pct populated after cross-aggregate UPDATE'),

-- ---- VIEW TESTS ----
(80, 'v_policy_detail_compiles',      'VIEW',     'v_policy_detail',     'ROW_COUNT','>=0','v_policy_detail returns results'),
(81, 'v_claims_analysis_compiles',    'VIEW',     'v_claims_analysis',   'ROW_COUNT','>=0','v_claims_analysis returns results'),
(82, 'v_exec_kpi_compiles',           'VIEW',     'v_exec_kpi_summary',  'ROW_COUNT','>=0','v_exec_kpi_summary returns results');
