-- =============================================================================
-- [META] Generated by: sybase-to-snowflake skill v0.3.0
-- [META] Purpose:       Reconciliation queries — 42-test validation suite
-- [META] Converted at:  2026-04-02
-- =============================================================================
--
-- Runs all 42 test cases from test_expected_results and logs results
-- to test_execution_log. Execute AFTER seed data has been loaded and
-- all DML layers have been processed.
--
-- Each query:
--   1. Evaluates the assertion against the converted Snowflake objects
--   2. INSERTs a PASS/FAIL record into test_execution_log
--   3. Groups by test_category for reporting
--
-- Execution order:
--   1. Run tests/test_ddl.sql       → creates test_expected_results, test_execution_log
--   2. Run simple_tier.sql          → creates 6 staging DDL tables
--   3. Run tests/seed_data.sql      → populates staging tables
--   4. Run complex_tier_dims_facts  → creates dim/fact tables + loads dim_date
--   5. Run DML for dims and facts   → populates dimension and fact tables
--   6. Run complex_tier_procs_aggs  → creates procedures, agg tables, views
--   7. Run this file                → validates all 42 test cases
-- =============================================================================


-- ============================================================
-- STAGING DDL TESTS (6 tests)
-- Validates column counts match Sybase source after conversion
-- ============================================================

-- T1: stg_policies column count
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 1, 'stg_policies_column_count',
       COUNT(*)::VARCHAR, '15',
       CASE WHEN COUNT(*) = 15 THEN 'PASS' ELSE 'FAIL' END
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CURRENT_SCHEMA() AND TABLE_NAME = 'STG_POLICIES';

-- T2: stg_customers column count
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 2, 'stg_customers_column_count',
       COUNT(*)::VARCHAR, '19',
       CASE WHEN COUNT(*) = 19 THEN 'PASS' ELSE 'FAIL' END
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CURRENT_SCHEMA() AND TABLE_NAME = 'STG_CUSTOMERS';

-- T3: stg_claims column count
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 3, 'stg_claims_column_count',
       COUNT(*)::VARCHAR, '19',
       CASE WHEN COUNT(*) = 19 THEN 'PASS' ELSE 'FAIL' END
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CURRENT_SCHEMA() AND TABLE_NAME = 'STG_CLAIMS';

-- T4: stg_agents column count
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 4, 'stg_agents_column_count',
       COUNT(*)::VARCHAR, '17',
       CASE WHEN COUNT(*) = 17 THEN 'PASS' ELSE 'FAIL' END
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CURRENT_SCHEMA() AND TABLE_NAME = 'STG_AGENTS';

-- T5: stg_products column count
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 5, 'stg_products_column_count',
       COUNT(*)::VARCHAR, '15',
       CASE WHEN COUNT(*) = 15 THEN 'PASS' ELSE 'FAIL' END
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CURRENT_SCHEMA() AND TABLE_NAME = 'STG_PRODUCTS';

-- T6: stg_payments column count
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 6, 'stg_payments_column_count',
       COUNT(*)::VARCHAR, '14',
       CASE WHEN COUNT(*) = 14 THEN 'PASS' ELSE 'FAIL' END
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = CURRENT_SCHEMA() AND TABLE_NAME = 'STG_PAYMENTS';


-- ============================================================
-- DIM_DATE TESTS (8 tests)
-- ============================================================

-- T10: dim_date row count = 11,323
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 10, 'dim_date_row_count',
       COUNT(*)::VARCHAR, '11323',
       CASE WHEN COUNT(*) = 11323 THEN 'PASS' ELSE 'FAIL' END
FROM dim_date;

-- T11: First date key = 20000101
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 11, 'dim_date_start_boundary',
       MIN(date_key)::VARCHAR, '20000101',
       CASE WHEN MIN(date_key) = 20000101 THEN 'PASS' ELSE 'FAIL' END
FROM dim_date;

-- T12: Last date key = 20301231
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 12, 'dim_date_end_boundary',
       MAX(date_key)::VARCHAR, '20301231',
       CASE WHEN MAX(date_key) = 20301231 THEN 'PASS' ELSE 'FAIL' END
FROM dim_date;

-- T13: Leap day 2024-02-29 exists
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 13, 'dim_date_leap_day',
       COUNT(*)::VARCHAR, '1',
       CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END
FROM dim_date WHERE date_key = 20240229;

-- T14: 2024-01-31 is_month_end = 'Y'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 14, 'dim_date_month_end_flag',
       is_month_end, 'Y',
       CASE WHEN is_month_end = 'Y' THEN 'PASS' ELSE 'FAIL' END
FROM dim_date WHERE date_key = 20240131;

-- T15: 2024-12-31 is_year_end = 'Y'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 15, 'dim_date_year_end_flag',
       is_year_end, 'Y',
       CASE WHEN is_year_end = 'Y' THEN 'PASS' ELSE 'FAIL' END
FROM dim_date WHERE date_key = 20241231;

-- T16: 2024-04-01 fiscal_year = 2024 (Apr is FY start)
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 16, 'dim_date_fiscal_year_apr',
       fiscal_year::VARCHAR, '2024',
       CASE WHEN fiscal_year = 2024 THEN 'PASS' ELSE 'FAIL' END
FROM dim_date WHERE date_key = 20240401;

-- T17: 2024-03-31 fiscal_year = 2023 (Mar is prior FY)
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 17, 'dim_date_fiscal_year_mar',
       fiscal_year::VARCHAR, '2023',
       CASE WHEN fiscal_year = 2023 THEN 'PASS' ELSE 'FAIL' END
FROM dim_date WHERE date_key = 20240331;


-- ============================================================
-- DIM_PRODUCT SCD1 / MERGE TESTS (4 tests)
-- ============================================================

-- T20: 6 products loaded
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 20, 'dim_product_initial_count',
       COUNT(*)::VARCHAR, '6',
       CASE WHEN COUNT(*) = 6 THEN 'PASS' ELSE 'FAIL' END
FROM dim_product;

-- T21: AUTO-01 lob_description = 'Personal Auto'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 21, 'dim_product_lob_auto',
       lob_description, 'Personal Auto',
       CASE WHEN lob_description = 'Personal Auto' THEN 'PASS' ELSE 'FAIL' END
FROM dim_product WHERE product_code = 'AUTO-01';

-- T22: LIFE-01 lob_description = 'Life and Annuity'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 22, 'dim_product_lob_life',
       lob_description, 'Life and Annuity',
       CASE WHEN lob_description = 'Life and Annuity' THEN 'PASS' ELSE 'FAIL' END
FROM dim_product WHERE product_code = 'LIFE-01';

-- T23: LIFE-01 is_active = 'N' (discontinued)
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 23, 'dim_product_inactive_flag',
       is_active, 'N',
       CASE WHEN is_active = 'N' THEN 'PASS' ELSE 'FAIL' END
FROM dim_product WHERE product_code = 'LIFE-01';


-- ============================================================
-- DIM_AGENT SCD2 TESTS (3 tests)
-- ============================================================

-- T30: 5 agent records on initial load
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 30, 'dim_agent_initial_count',
       COUNT(*)::VARCHAR, '5',
       CASE WHEN COUNT(*) = 5 THEN 'PASS' ELSE 'FAIL' END
FROM dim_agent;

-- T31: All 5 have scd_current_flag = 'Y'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 31, 'dim_agent_scd_current_flag',
       COUNT(*)::VARCHAR, '5',
       CASE WHEN COUNT(*) = 5 THEN 'PASS' ELSE 'FAIL' END
FROM dim_agent WHERE scd_current_flag = 'Y';

-- T32: Agent 104 is_active = 'N'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 32, 'dim_agent_inactive_preserved',
       is_active, 'N',
       CASE WHEN is_active = 'N' THEN 'PASS' ELSE 'FAIL' END
FROM dim_agent WHERE agent_id = 104 AND scd_current_flag = 'Y';


-- ============================================================
-- DIM_CUSTOMER SCD2 TESTS (8 tests)
-- ============================================================

-- T40: 8 customer records on initial load
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 40, 'dim_cust_initial_count',
       COUNT(*)::VARCHAR, '8',
       CASE WHEN COUNT(*) = 8 THEN 'PASS' ELSE 'FAIL' END
FROM dim_customer WHERE scd_current_flag = 'Y';

-- T41: Customer 5004 (score=800) → 'Exceptional (800+)'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 41, 'dim_cust_credit_exceptional',
       credit_band, 'Exceptional (800+)',
       CASE WHEN credit_band = 'Exceptional (800+)' THEN 'PASS' ELSE 'FAIL' END
FROM dim_customer WHERE customer_id = 5004 AND scd_current_flag = 'Y';

-- T42: Customer 5001 (score=780) → 'Very Good (740-799)'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 42, 'dim_cust_credit_very_good',
       credit_band, 'Very Good (740-799)',
       CASE WHEN credit_band = 'Very Good (740-799)' THEN 'PASS' ELSE 'FAIL' END
FROM dim_customer WHERE customer_id = 5001 AND scd_current_flag = 'Y';

-- T43: Customer 5003 (score=670) → 'Good (670-739)'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 43, 'dim_cust_credit_good',
       credit_band, 'Good (670-739)',
       CASE WHEN credit_band = 'Good (670-739)' THEN 'PASS' ELSE 'FAIL' END
FROM dim_customer WHERE customer_id = 5003 AND scd_current_flag = 'Y';

-- T44: Customer 5002 (score=580) → 'Fair (580-669)'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 44, 'dim_cust_credit_fair',
       credit_band, 'Fair (580-669)',
       CASE WHEN credit_band = 'Fair (580-669)' THEN 'PASS' ELSE 'FAIL' END
FROM dim_customer WHERE customer_id = 5002 AND scd_current_flag = 'Y';

-- T45: Customer 5007 (score=520) → 'Poor (<580)'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 45, 'dim_cust_credit_poor',
       credit_band, 'Poor (<580)',
       CASE WHEN credit_band = 'Poor (<580)' THEN 'PASS' ELSE 'FAIL' END
FROM dim_customer WHERE customer_id = 5007 AND scd_current_flag = 'Y';

-- T46: Customer 5005 (NULL score) → 'Unknown'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 46, 'dim_cust_credit_unknown',
       credit_band, 'Unknown',
       CASE WHEN credit_band = 'Unknown' THEN 'PASS' ELSE 'FAIL' END
FROM dim_customer WHERE customer_id = 5005 AND scd_current_flag = 'Y';

-- T47: Customer 5001 (CT) → region = 'Northeast'
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 47, 'dim_cust_region_northeast',
       region, 'Northeast',
       CASE WHEN region = 'Northeast' THEN 'PASS' ELSE 'FAIL' END
FROM dim_customer WHERE customer_id = 5001 AND scd_current_flag = 'Y';


-- ============================================================
-- FACT TABLE TESTS (7 tests)
-- ============================================================

-- T50: 10 policies loaded
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 50, 'fact_policy_load_count',
       COUNT(*)::VARCHAR, '10',
       CASE WHEN COUNT(*) = 10 THEN 'PASS' ELSE 'FAIL' END
FROM fact_policy;

-- T51: Policy 1001 effective_date_key = 20240115
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 51, 'fact_policy_date_key_format',
       effective_date_key::VARCHAR, '20240115',
       CASE WHEN effective_date_key = 20240115 THEN 'PASS' ELSE 'FAIL' END
FROM fact_policy WHERE policy_id = 1001;

-- T52: Policy 1001 term_days = 366 (2024-01-15 to 2025-01-15, leap year)
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 52, 'fact_policy_term_days',
       policy_term_days::VARCHAR, '366',
       CASE WHEN policy_term_days = 366 THEN 'PASS' ELSE 'FAIL' END
FROM fact_policy WHERE policy_id = 1001;

-- T60: 6 claims loaded
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 60, 'fact_claims_load_count',
       COUNT(*)::VARCHAR, '6',
       CASE WHEN COUNT(*) = 6 THEN 'PASS' ELSE 'FAIL' END
FROM fact_claims;

-- T61: Claim 3001 report_lag_days = 2
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 61, 'fact_claims_report_lag',
       claim_report_lag_days::VARCHAR, '2',
       CASE WHEN claim_report_lag_days = 2 THEN 'PASS' ELSE 'FAIL' END
FROM fact_claims WHERE claim_id = 3001;

-- T62: Claim 3001 settlement_days = 73 (Jun 3 → Aug 15)
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 62, 'fact_claims_settlement_days',
       claim_settlement_days::VARCHAR, '73',
       CASE WHEN claim_settlement_days = 73 THEN 'PASS' ELSE 'FAIL' END
FROM fact_claims WHERE claim_id = 3001;

-- T63: Claim 3002 closed_date_key IS NULL (open claim)
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 63, 'fact_claims_null_closed_key',
       COALESCE(closed_date_key::VARCHAR, 'NULL'), 'NULL',
       CASE WHEN closed_date_key IS NULL THEN 'PASS' ELSE 'FAIL' END
FROM fact_claims WHERE claim_id = 3002;


-- ============================================================
-- AGGREGATION TESTS (2 tests)
-- ============================================================

-- T70: agg_policy_monthly has rows
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 70, 'agg_policy_monthly_populated',
       COUNT(*)::VARCHAR, '>0',
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END
FROM agg_policy_monthly;

-- T71: agg_claims_monthly has rows
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 71, 'agg_claims_monthly_populated',
       COUNT(*)::VARCHAR, '>0',
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END
FROM agg_claims_monthly;


-- ============================================================
-- VIEW TESTS (3 tests)
-- ============================================================

-- T80: v_policy_detail returns rows
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 80, 'v_policy_detail_returns_rows',
       COUNT(*)::VARCHAR, '>=0',
       CASE WHEN COUNT(*) >= 0 THEN 'PASS' ELSE 'FAIL' END
FROM v_policy_detail;

-- T81: v_claims_analysis returns rows
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 81, 'v_claims_analysis_returns_rows',
       COUNT(*)::VARCHAR, '>=0',
       CASE WHEN COUNT(*) >= 0 THEN 'PASS' ELSE 'FAIL' END
FROM v_claims_analysis;

-- T82: v_exec_kpi_summary returns rows
INSERT INTO test_execution_log (test_id, test_name, actual_value, expected_value, result)
SELECT 82, 'v_exec_kpi_returns_rows',
       COUNT(*)::VARCHAR, '>=0',
       CASE WHEN COUNT(*) >= 0 THEN 'PASS' ELSE 'FAIL' END
FROM v_exec_kpi_summary;


-- ============================================================
-- TEST SUMMARY REPORT
-- ============================================================
SELECT
    '========== TEST EXECUTION SUMMARY ==========' AS header
UNION ALL
SELECT
    'Total tests: ' || COUNT(*)::VARCHAR ||
    ' | PASS: ' || SUM(CASE WHEN result = 'PASS' THEN 1 ELSE 0 END)::VARCHAR ||
    ' | FAIL: ' || SUM(CASE WHEN result = 'FAIL' THEN 1 ELSE 0 END)::VARCHAR ||
    ' | ERROR: ' || SUM(CASE WHEN result = 'ERROR' THEN 1 ELSE 0 END)::VARCHAR
FROM test_execution_log;

-- Detail of any failures:
SELECT test_id, test_name, actual_value, expected_value, result, error_message
FROM test_execution_log
WHERE result <> 'PASS'
ORDER BY test_id;

-- Category breakdown:
SELECT
    ter.test_category,
    COUNT(*)                                            AS total_tests,
    SUM(CASE WHEN tel.result = 'PASS' THEN 1 ELSE 0 END) AS pass_count,
    SUM(CASE WHEN tel.result = 'FAIL' THEN 1 ELSE 0 END) AS fail_count
FROM test_execution_log tel
INNER JOIN test_expected_results ter ON ter.test_id = tel.test_id
GROUP BY ter.test_category
ORDER BY ter.test_category;
