-- =============================================================================
-- [META] Generated by: sybase-to-snowflake skill v0.3.0
-- [META] Purpose:       Test execution script — runs converted SQL against seed data
-- [META] Converted at:  2026-04-02
-- =============================================================================
--
-- Execution order follows dependency_graph.json topological sort:
--   Layer 0: DDL staging → DDL dimensions → DDL facts → DDL audit → seed data
--   Layer 1: DML dim_date (GENERATOR)
--   Layer 2: DML dim_product (MERGE / SCD1)
--   Layer 3: DML dim_agent (SCD2 — initial load)
--   Layer 4: DML dim_customer (SCD2 — initial load)
--   Layer 5: DML fact_policy, fact_claims, fact_payments
--   Layer 6: DML aggregation + cross-aggregate UPDATE
--   Layer 7: DDL views
--   Layer 8: Stored procedures
--
-- Prerequisites:
--   1. Create a test schema:  CREATE SCHEMA IF NOT EXISTS <db>._SYBASE_MIGRATION_TEST;
--   2. USE SCHEMA <db>._SYBASE_MIGRATION_TEST;
--   3. Run this script in order (each statement separated by ;)
-- =============================================================================


-- ============================================================
-- LAYER 0: DDL — Create all tables
-- ============================================================

-- Step 0a: Run simple_tier.sql (6 staging tables from basic series)
-- Step 0b: Run medium_tier.sql (9 enhanced staging tables + DML from ETL series)
-- Step 0c: Run complex_tier_dims_facts.sql (dim_date DDL, dim_product DDL,
--          dim_agent DDL, dim_customer DDL, fact_policy DDL, fact_claims DDL,
--          fact_payments DDL)
-- Step 0d: Run complex_tier_procs_aggs.sql section 1 (etl_audit_log DDL)

-- Then load seed data:
-- Step 0e: Run tests/seed_data.sql

-- Then create test infrastructure:
-- Step 0f: Run tests/test_ddl.sql


-- ============================================================
-- LAYER 1: dim_date — GENERATOR INSERT
-- ============================================================
-- Run: complex_tier_dims_facts.sql (dim_date INSERT + GENERATOR section)
-- Verify:
SELECT 'dim_date_row_count' AS test_name,
       COUNT(*)             AS actual_value,
       11323                AS expected_value,
       CASE WHEN COUNT(*) = 11323 THEN 'PASS' ELSE 'FAIL' END AS result
FROM dim_date;


-- ============================================================
-- LAYER 2: dim_product — MERGE (SCD1)
-- ============================================================
-- Run: complex_tier_dims_facts.sql (dim_product MERGE section)
-- Verify:
SELECT 'dim_product_load_count' AS test_name,
       COUNT(*)                 AS actual_value,
       6                        AS expected_value,
       CASE WHEN COUNT(*) = 6 THEN 'PASS' ELSE 'FAIL' END AS result
FROM dim_product;


-- ============================================================
-- LAYER 3: dim_agent — SCD2 initial load
-- ============================================================
-- Run: complex_tier_dims_facts.sql (dim_agent expire UPDATE, then INSERT)
-- Note: SCD2 expire UPDATE won't fire on initial load (no prior records)
-- Verify:
SELECT 'dim_agent_initial_count' AS test_name,
       COUNT(*)                  AS actual_value,
       5                         AS expected_value,
       CASE WHEN COUNT(*) = 5 THEN 'PASS' ELSE 'FAIL' END AS result
FROM dim_agent
WHERE scd_current_flag = 'Y';


-- ============================================================
-- LAYER 4: dim_customer — SCD2 initial load
-- ============================================================
-- Run: complex_tier_dims_facts.sql (dim_customer expire UPDATE, then INSERT)
-- Verify:
SELECT 'dim_customer_initial_count' AS test_name,
       COUNT(*)                     AS actual_value,
       8                            AS expected_value,
       CASE WHEN COUNT(*) = 8 THEN 'PASS' ELSE 'FAIL' END AS result
FROM dim_customer
WHERE scd_current_flag = 'Y';


-- ============================================================
-- LAYER 5: fact tables
-- ============================================================
-- Run: complex_tier_dims_facts.sql (fact_policy INSERT, fact_claims INSERT,
--      fact_payments INSERT sections)

-- Verify fact_policy:
SELECT 'fact_policy_load_count' AS test_name,
       COUNT(*)                 AS actual_value,
       10                       AS expected_value,
       CASE WHEN COUNT(*) = 10 THEN 'PASS' ELSE 'FAIL' END AS result
FROM fact_policy;

-- Verify fact_claims:
SELECT 'fact_claims_load_count' AS test_name,
       COUNT(*)                 AS actual_value,
       6                        AS expected_value,
       CASE WHEN COUNT(*) = 6 THEN 'PASS' ELSE 'FAIL' END AS result
FROM fact_claims;


-- ============================================================
-- LAYER 6: Aggregation
-- ============================================================
-- Run: complex_tier_procs_aggs.sql (agg_policy_monthly DDL+DML,
--      agg_claims_monthly DDL+DML, cross-aggregate UPDATE)

-- Verify:
SELECT 'agg_policy_monthly_populated' AS test_name,
       COUNT(*)                       AS actual_value,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM agg_policy_monthly;

SELECT 'agg_claims_monthly_populated' AS test_name,
       COUNT(*)                       AS actual_value,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM agg_claims_monthly;


-- ============================================================
-- LAYER 7: Views
-- ============================================================
-- Run: simple_tier.sql (v_policy_detail, v_claims_analysis)
-- Run: complex_tier_procs_aggs.sql (v_exec_kpi_summary)

-- Verify views return data:
SELECT 'v_policy_detail_returns_rows' AS test_name,
       COUNT(*)                       AS actual_value,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM v_policy_detail;

SELECT 'v_claims_analysis_returns_rows' AS test_name,
       COUNT(*)                         AS actual_value,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM v_claims_analysis;

SELECT 'v_exec_kpi_summary_returns_rows' AS test_name,
       COUNT(*)                          AS actual_value,
       CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
FROM v_exec_kpi_summary;


-- ============================================================
-- LAYER 8: Stored procedures
-- ============================================================
-- Run: complex_tier_procs_aggs.sql (CREATE OR REPLACE PROCEDURE sections)
-- Procedures to validate:
--   sp_validate_claims   — CALL sp_validate_claims()
--   sp_run_etl_pipeline  — CALL sp_run_etl_pipeline()
--   sp_archive_stale_policies — CALL sp_archive_stale_policies(90)
--   sp_recalculate_kpis  — CALL sp_recalculate_kpis()

-- Verify etl_audit_log entries after procedure call:
-- CALL sp_run_etl_pipeline();
-- SELECT 'sp_etl_pipeline_runs' AS test_name,
--        COUNT(*)               AS actual_value,
--        CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END AS result
-- FROM etl_audit_log;


-- ============================================================
-- SUMMARY: Collect all test results
-- ============================================================
-- After running all layers above, execute reconciliation_queries.sql
-- for the full 42-test validation suite.
