-- =============================================================================
-- [META] Generated by: sybase-to-snowflake skill v0.3.0
-- [META] Purpose:       Test infrastructure DDL for validation harness
-- [META] Converted at:  2026-04-02
-- =============================================================================
--
-- Creates:
--   1. test_expected_results — expected outcome reference table
--   2. test_execution_log   — records test run results
-- =============================================================================


-- ============================================================
-- Test expected results reference
-- ============================================================
CREATE OR REPLACE TABLE test_expected_results (
    test_id             INT             NOT NULL,
    test_name           VARCHAR(200)    NOT NULL,
    test_category       VARCHAR(50)     NOT NULL,   -- STG_DDL, DIM_DATE, SCD1, SCD2, FACT, DQ, AGG, VIEW, PROC
    target_object       VARCHAR(100)    NOT NULL,
    assertion_type      VARCHAR(30)     NOT NULL,   -- ROW_COUNT, VALUE_CHECK, COLUMN_COUNT, EXISTS, NOT_EXISTS, NULL_CHECK
    expected_value      VARCHAR(500)    NULL,
    description         VARCHAR(500)    NOT NULL,
    PRIMARY KEY (test_id)
);

-- ============================================================
-- Test execution log
-- ============================================================
CREATE OR REPLACE TABLE test_execution_log (
    run_id              INT AUTOINCREMENT NOT NULL PRIMARY KEY,
    test_id             INT             NOT NULL,
    test_name           VARCHAR(200)    NOT NULL,
    executed_at         TIMESTAMP_NTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    actual_value        VARCHAR(500)    NULL,
    expected_value      VARCHAR(500)    NULL,
    result              VARCHAR(10)     NOT NULL,   -- PASS, FAIL, ERROR
    error_message       VARCHAR(1000)   NULL
);


-- ============================================================
-- Populate expected results (42 test cases)
-- ============================================================
INSERT INTO test_expected_results VALUES

-- ---- STAGING DDL TESTS (6 tests) ----
(1,  'stg_policies_column_count',    'STG_DDL',  'stg_policies',  'COLUMN_COUNT', '15',   'stg_policies has 15 columns after conversion'),
(2,  'stg_customers_column_count',   'STG_DDL',  'stg_customers', 'COLUMN_COUNT', '19',   'stg_customers has 19 columns after conversion'),
(3,  'stg_claims_column_count',      'STG_DDL',  'stg_claims',    'COLUMN_COUNT', '19',   'stg_claims has 19 columns after conversion'),
(4,  'stg_agents_column_count',      'STG_DDL',  'stg_agents',    'COLUMN_COUNT', '17',   'stg_agents has 17 columns after conversion'),
(5,  'stg_products_column_count',    'STG_DDL',  'stg_products',  'COLUMN_COUNT', '15',   'stg_products has 15 columns after conversion'),
(6,  'stg_payments_column_count',    'STG_DDL',  'stg_payments',  'COLUMN_COUNT', '14',   'stg_payments has 14 columns after conversion'),

-- ---- DIM_DATE TESTS (8 tests) ----
(10, 'dim_date_row_count',           'DIM_DATE', 'dim_date',      'ROW_COUNT',    '11323','GENERATOR produces exactly 11,323 rows (2000-01-01 to 2030-12-31)'),
(11, 'dim_date_start_boundary',      'DIM_DATE', 'dim_date',      'EXISTS',       '20000101', 'First date key = 2000-01-01'),
(12, 'dim_date_end_boundary',        'DIM_DATE', 'dim_date',      'EXISTS',       '20301231', 'Last date key = 2030-12-31'),
(13, 'dim_date_leap_day',            'DIM_DATE', 'dim_date',      'EXISTS',       '20240229', 'Leap day 2024-02-29 present'),
(14, 'dim_date_month_end_flag',      'DIM_DATE', 'dim_date',      'VALUE_CHECK',  'Y',    '2024-01-31 has is_month_end = Y'),
(15, 'dim_date_year_end_flag',       'DIM_DATE', 'dim_date',      'VALUE_CHECK',  'Y',    '2024-12-31 has is_year_end = Y'),
(16, 'dim_date_fiscal_year_apr',     'DIM_DATE', 'dim_date',      'VALUE_CHECK',  '2024', '2024-04-01 fiscal_year = 2024 (Apr = FY start)'),
(17, 'dim_date_fiscal_year_mar',     'DIM_DATE', 'dim_date',      'VALUE_CHECK',  '2023', '2024-03-31 fiscal_year = 2023 (Mar = prior FY)'),

-- ---- DIM_PRODUCT SCD1 MERGE TESTS (4 tests) ----
(20, 'dim_product_initial_count',    'SCD1',     'dim_product',   'ROW_COUNT',    '6',    '6 products loaded on initial MERGE'),
(21, 'dim_product_lob_auto',         'SCD1',     'dim_product',   'VALUE_CHECK',  'Personal Auto', 'AUTO-01 lob_description = Personal Auto'),
(22, 'dim_product_lob_life',         'SCD1',     'dim_product',   'VALUE_CHECK',  'Life and Annuity', 'LIFE-01 lob_description = Life and Annuity'),
(23, 'dim_product_inactive_flag',    'SCD1',     'dim_product',   'VALUE_CHECK',  'N',    'LIFE-01 is_active = N (discontinued)'),

-- ---- DIM_AGENT SCD2 TESTS (3 tests) ----
(30, 'dim_agent_initial_count',      'SCD2',     'dim_agent',     'ROW_COUNT',    '5',    '5 agent records on initial load'),
(31, 'dim_agent_scd_current_flag',   'SCD2',     'dim_agent',     'ROW_COUNT',    '5',    'All 5 initial records have scd_current_flag = Y'),
(32, 'dim_agent_inactive_preserved', 'SCD2',     'dim_agent',     'VALUE_CHECK',  'N',    'Agent 104 is_active = N preserved'),

-- ---- DIM_CUSTOMER SCD2 TESTS (8 tests) ----
(40, 'dim_cust_initial_count',       'SCD2',     'dim_customer',  'ROW_COUNT',    '8',    '8 customer records on initial load'),
(41, 'dim_cust_credit_exceptional',  'SCD2',     'dim_customer',  'VALUE_CHECK',  'Exceptional (800+)', 'Customer 5004 credit_band = Exceptional (800+) [score=800]'),
(42, 'dim_cust_credit_very_good',    'SCD2',     'dim_customer',  'VALUE_CHECK',  'Very Good (740-799)', 'Customer 5001 credit_band = Very Good (740-799) [score=780]'),
(43, 'dim_cust_credit_good',         'SCD2',     'dim_customer',  'VALUE_CHECK',  'Good (670-739)', 'Customer 5003 credit_band = Good (670-739) [score=670]'),
(44, 'dim_cust_credit_fair',         'SCD2',     'dim_customer',  'VALUE_CHECK',  'Fair (580-669)', 'Customer 5002 credit_band = Fair (580-669) [score=580]'),
(45, 'dim_cust_credit_poor',         'SCD2',     'dim_customer',  'VALUE_CHECK',  'Poor (<580)', 'Customer 5007 credit_band = Poor (<580) [score=520]'),
(46, 'dim_cust_credit_unknown',      'SCD2',     'dim_customer',  'VALUE_CHECK',  'Unknown', 'Customer 5005 credit_band = Unknown [NULL score]'),
(47, 'dim_cust_region_northeast',    'SCD2',     'dim_customer',  'VALUE_CHECK',  'Northeast', 'Customer 5001 region = Northeast [state=CT]'),

-- ---- FACT_POLICY TESTS (4 tests) ----
(50, 'fact_policy_load_count',       'FACT',     'fact_policy',   'ROW_COUNT',    '10',   '10 policies loaded'),
(51, 'fact_policy_date_key_format',  'FACT',     'fact_policy',   'VALUE_CHECK',  '20240115', 'Policy 1001 effective_date_key = 20240115'),
(52, 'fact_policy_term_days',        'FACT',     'fact_policy',   'VALUE_CHECK',  '366',  'Policy 1001 term_days = 366 (2024 leap year)'),

-- ---- FACT_CLAIMS TESTS (4 tests) ----
(60, 'fact_claims_load_count',       'FACT',     'fact_claims',   'ROW_COUNT',    '6',    '6 claims loaded'),
(61, 'fact_claims_report_lag',       'FACT',     'fact_claims',   'VALUE_CHECK',  '2',    'Claim 3001 report_lag_days = 2 (Jun 1 → Jun 3)'),
(62, 'fact_claims_settlement_days',  'FACT',     'fact_claims',   'VALUE_CHECK',  '73',   'Claim 3001 settlement_days = 73 (Jun 3 → Aug 15)'),
(63, 'fact_claims_null_closed_key',  'FACT',     'fact_claims',   'NULL_CHECK',   'NULL', 'Claim 3002 closed_date_key IS NULL (open claim)'),

-- ---- AGGREGATION TESTS (2 tests) ----
(70, 'agg_policy_monthly_populated', 'AGG',      'agg_policy_monthly',  'ROW_COUNT', '>0', 'agg_policy_monthly has rows after load'),
(71, 'agg_claims_monthly_populated', 'AGG',      'agg_claims_monthly',  'ROW_COUNT', '>0', 'agg_claims_monthly has rows after load'),

-- ---- VIEW TESTS (3 tests) ----
(80, 'v_policy_detail_returns_rows', 'VIEW',     'v_policy_detail',     'ROW_COUNT', '>=0', 'v_policy_detail returns results'),
(81, 'v_claims_analysis_returns_rows','VIEW',    'v_claims_analysis',   'ROW_COUNT', '>=0', 'v_claims_analysis returns results'),
(82, 'v_exec_kpi_returns_rows',      'VIEW',     'v_exec_kpi_summary',  'ROW_COUNT', '>=0', 'v_exec_kpi_summary returns results');
