-- =============================================================================
-- [META] Generated by: sybase-to-snowflake skill v0.3.0, Step 12
-- [META] Source pipeline: run_20260402_000000
-- [META] Generated at:    2026-04-02
-- [META] Total recommendations: 22 (14 auto-apply, 8 manual-review)
-- =============================================================================

-- ═══════════════════════════════════════════════════════════════
-- AUTO-APPLY RECOMMENDATIONS
-- These are safe, additive changes approved for automatic application.
-- ═══════════════════════════════════════════════════════════════

-- ── O1: CLUSTERING KEYS ─────────────────────────────────────

-- R001 | fact_policy | HIGH
-- Cluster on date dimension key + product for range queries in v_policy_detail, agg_policy_monthly
ALTER TABLE fact_policy
  CLUSTER BY (effective_date_key, product_key);

-- R002 | fact_claims | HIGH
-- Cluster on incident date + product for range queries in v_claims_analysis, agg_claims_monthly
ALTER TABLE fact_claims
  CLUSTER BY (incident_date_key, product_key);

-- R003 | fact_payments | HIGH
-- Cluster on payment date + customer for payment analysis queries
ALTER TABLE fact_payments
  CLUSTER BY (payment_date_key, customer_key);


-- ── O2: TRANSIENT TABLES ────────────────────────────────────
-- Note: To apply these, change CREATE OR REPLACE TABLE → CREATE OR REPLACE TRANSIENT TABLE
-- in ddl_staging.sql. The ALTER statements below convert existing tables.

-- R004 | stg_policies | HIGH — truncate-and-reload staging, no Fail-safe needed
CREATE OR REPLACE TRANSIENT TABLE stg_policies AS SELECT * FROM stg_policies;

-- R005 | stg_customers | HIGH
CREATE OR REPLACE TRANSIENT TABLE stg_customers AS SELECT * FROM stg_customers;

-- R006 | stg_claims | HIGH
CREATE OR REPLACE TRANSIENT TABLE stg_claims AS SELECT * FROM stg_claims;

-- R007 | stg_agents | HIGH
CREATE OR REPLACE TRANSIENT TABLE stg_agents AS SELECT * FROM stg_agents;

-- R008 | stg_products | HIGH
CREATE OR REPLACE TRANSIENT TABLE stg_products AS SELECT * FROM stg_products;

-- R009 | stg_payments | HIGH
CREATE OR REPLACE TRANSIENT TABLE stg_payments AS SELECT * FROM stg_payments;


-- ── O5: INFORMATIONAL CONSTRAINTS ───────────────────────────
-- These are not enforced by Snowflake but enable BI join inference and join elimination.

-- R017 | Named PK constraints for BI tool discovery
ALTER TABLE dim_product   ADD CONSTRAINT pk_dim_product   PRIMARY KEY (product_key);
ALTER TABLE dim_agent     ADD CONSTRAINT pk_dim_agent     PRIMARY KEY (agent_key);
ALTER TABLE dim_customer  ADD CONSTRAINT pk_dim_customer  PRIMARY KEY (customer_key);

-- R014 | fact_policy FK constraints | HIGH
ALTER TABLE fact_policy ADD CONSTRAINT fk_fact_policy_customer
  FOREIGN KEY (customer_key) REFERENCES dim_customer (customer_key);
ALTER TABLE fact_policy ADD CONSTRAINT fk_fact_policy_agent
  FOREIGN KEY (agent_key) REFERENCES dim_agent (agent_key);
ALTER TABLE fact_policy ADD CONSTRAINT fk_fact_policy_product
  FOREIGN KEY (product_key) REFERENCES dim_product (product_key);
ALTER TABLE fact_policy ADD CONSTRAINT fk_fact_policy_eff_date
  FOREIGN KEY (effective_date_key) REFERENCES dim_date (date_key);
ALTER TABLE fact_policy ADD CONSTRAINT fk_fact_policy_exp_date
  FOREIGN KEY (expiry_date_key) REFERENCES dim_date (date_key);

-- R015 | fact_claims FK constraints | HIGH
ALTER TABLE fact_claims ADD CONSTRAINT fk_fact_claims_customer
  FOREIGN KEY (customer_key) REFERENCES dim_customer (customer_key);
ALTER TABLE fact_claims ADD CONSTRAINT fk_fact_claims_product
  FOREIGN KEY (product_key) REFERENCES dim_product (product_key);
ALTER TABLE fact_claims ADD CONSTRAINT fk_fact_claims_inc_date
  FOREIGN KEY (incident_date_key) REFERENCES dim_date (date_key);
ALTER TABLE fact_claims ADD CONSTRAINT fk_fact_claims_rpt_date
  FOREIGN KEY (reported_date_key) REFERENCES dim_date (date_key);

-- R016 | fact_payments FK constraints | HIGH
ALTER TABLE fact_payments ADD CONSTRAINT fk_fact_payments_customer
  FOREIGN KEY (customer_key) REFERENCES dim_customer (customer_key);
ALTER TABLE fact_payments ADD CONSTRAINT fk_fact_payments_date
  FOREIGN KEY (payment_date_key) REFERENCES dim_date (date_key);


-- ── O8: STORAGE TUNING (DATA_RETENTION_TIME_IN_DAYS) ────────

-- R020 | Fact tables: 90 days for audit trail and point-in-time recovery | MEDIUM
ALTER TABLE fact_policy   SET DATA_RETENTION_TIME_IN_DAYS = 90;
ALTER TABLE fact_claims   SET DATA_RETENTION_TIME_IN_DAYS = 90;
ALTER TABLE fact_payments SET DATA_RETENTION_TIME_IN_DAYS = 90;

-- R021 | Dimension tables: 14 days for SCD debugging and MERGE rollback | MEDIUM
ALTER TABLE dim_customer SET DATA_RETENTION_TIME_IN_DAYS = 14;
ALTER TABLE dim_agent    SET DATA_RETENTION_TIME_IN_DAYS = 14;
ALTER TABLE dim_product  SET DATA_RETENTION_TIME_IN_DAYS = 14;

-- R022 | Audit table: 90 days for compliance and batch investigation | MEDIUM
ALTER TABLE etl_audit_log SET DATA_RETENTION_TIME_IN_DAYS = 90;


-- ═══════════════════════════════════════════════════════════════
-- MANUAL REVIEW RECOMMENDATIONS
-- These require architecture decisions or Enterprise Edition.
-- Uncomment and modify as needed after review.
-- ═══════════════════════════════════════════════════════════════

-- ── O3: SEARCH OPTIMIZATION (Enterprise Edition required) ───

-- [MANUAL REVIEW] R010 | fact_policy | MEDIUM
-- Point lookups on policy_number for customer service / policy inquiry
-- ALTER TABLE fact_policy ADD SEARCH OPTIMIZATION ON EQUALITY(policy_number);

-- [MANUAL REVIEW] R011 | fact_claims | MEDIUM
-- Point lookups on claim_number for claims inquiry / adjuster workflow
-- ALTER TABLE fact_claims ADD SEARCH OPTIMIZATION ON EQUALITY(claim_number);

-- [MANUAL REVIEW] R012 | dim_customer | MEDIUM
-- Point lookups on customer_id (natural key) for customer service and SCD2 MERGE
-- ALTER TABLE dim_customer ADD SEARCH OPTIMIZATION ON EQUALITY(customer_id);


-- ── O4: QUERY ACCELERATION SERVICE ──────────────────────────

-- [MANUAL REVIEW] R013 | (target warehouse) | LOW
-- Ad-hoc analytics via v_policy_detail, v_claims_analysis, v_exec_kpi_summary
-- ALTER WAREHOUSE <your_warehouse> SET ENABLE_QUERY_ACCELERATION = TRUE
--   QUERY_ACCELERATION_MAX_SCALE_FACTOR = 8;


-- ── O6: DYNAMIC TABLE CANDIDATE ─────────────────────────────

-- [MANUAL REVIEW] R018 | agg_policy_monthly | MEDIUM
-- Single INSERT...SELECT aggregate — suitable for Dynamic Table conversion.
-- Note: agg_claims_monthly is NOT a candidate (has cross-aggregate UPDATE).
-- Replace existing CREATE TABLE + INSERT with:
--
-- CREATE OR REPLACE DYNAMIC TABLE agg_policy_monthly
--   TARGET_LAG = '1 hour'  -- Adjust based on freshness requirements
--   WAREHOUSE = <your_warehouse>
-- AS
-- SELECT
--     dd_eff.year_number,
--     dd_eff.month_number,
--     dd_eff.quarter_number,
--     COALESCE(dp.product_line, 'UNKNOWN') AS product_line,
--     COALESCE(dp.lob_code, 'UNKNOWN') AS lob_code,
--     COALESCE(da.channel_code, 'UNKNOWN') AS channel_code,
--     COALESCE(dc.region, 'UNKNOWN') AS region,
--     COALESCE(dc.state_code, 'XX') AS state_code,
--     fp.status_code,
--     COUNT(fp.policy_fact_key) AS policy_count,
--     SUM(CASE WHEN fp.status_code = 'CN' THEN 1 ELSE 0 END) AS cancelled_policy_count,
--     SUM(COALESCE(fp.annual_premium, 0)) AS total_annual_premium,
--     SUM(COALESCE(fp.earned_premium_amount, 0)) AS total_earned_premium,
--     SUM(COALESCE(fp.coverage_amount, 0)) AS total_coverage_amount,
--     CASE WHEN COUNT(fp.policy_fact_key) > 0
--          THEN ROUND(SUM(COALESCE(fp.annual_premium, 0)) / COUNT(fp.policy_fact_key), 2)
--          ELSE NULL END AS avg_premium_per_policy
-- FROM fact_policy fp
-- INNER JOIN dim_date dd_eff ON dd_eff.date_key = fp.effective_date_key
-- INNER JOIN dim_product dp ON dp.product_key = fp.product_key
-- INNER JOIN dim_agent da ON da.agent_key = fp.agent_key
-- INNER JOIN dim_customer dc ON dc.customer_key = fp.customer_key
-- WHERE dd_eff.year_number >= 2015
-- GROUP BY ALL;


-- ── O7: STREAMS + TASKS ROADMAP ─────────────────────────────

-- [MANUAL REVIEW] R019 | pipeline-level | LOW
-- Modernization path from batch ETL to near-real-time CDC:
--
-- Recommended Stream/Task DAG:
--   STREAM on stg_policies   → TASK refresh_dim_customer (MERGE SCD2)
--   STREAM on stg_customers  → TASK refresh_dim_customer (MERGE SCD2)
--   STREAM on stg_agents     → TASK refresh_dim_agent (MERGE SCD2)
--   STREAM on stg_products   → TASK refresh_dim_product (MERGE SCD1)
--   STREAM on stg_claims     → TASK refresh_fact_claims (INSERT)
--   STREAM on stg_payments   → TASK refresh_fact_payments (INSERT)
--
-- Task DAG structure (mirrors dependency_graph.json):
--   root_task: load_staging
--     → refresh_dimensions (dim_product, dim_agent, dim_customer)
--       → refresh_facts (fact_policy, fact_claims, fact_payments)
--         → refresh_aggregates (agg_policy_monthly, agg_claims_monthly)
--
-- Benefits:
--   - Process only changed rows (reduced compute cost)
--   - Near-real-time refresh instead of batch windows
--   - Built-in exactly-once semantics via Stream offsets
--   - Automatic retry and error handling via Task configuration
--
-- Prerequisites:
--   - Source system must support CDC or incremental extraction
--   - Evaluate freshness requirements per business domain
--   - This is an architectural decision — not auto-applied
